<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>GHOOMO PAKISTAN</title>


    <!-- footer -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- footer -->
    <!-- Dashboard icons -->
    <link rel="stylesheet" href="{{asset('plugins/fontawesome-free/css/all.min.css')}}">
    <!-- Dashboard icons -->
    <!-- banner -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="{{asset('dist/banner/css/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{asset('dist/banner/css/owl.theme.default.min.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/4.5.6/css/ionicons.min.css">
    <link rel="stylesheet" href="{{asset('dist/banner/css/animate.css')}}">
    <link rel="stylesheet" href="{{asset('dist/banner/css/style.css')}}">
    <!-- navbarthumkay -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="{{asset('dist/js/script.js')}}"></script>
    <!-- logocss -->
    <link rel="stylesheet" href="{{asset('dist/css/navcss/logo.css')}}">
    <!-- logocss -->

    <!-- footer -->
    <link rel="stylesheet" href="{{asset('plugins/fontawesome-free/css/style.css')}}">
    <!-- iCheck -->
    <!-- owl  -->
    <link rel="stylesheet" type="text/css" href="{{asset('dist/owl/owl.carousel.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('dist/owl/owlstyle.css')}}">
    <!----owl---->
    <!-- custom div -->
    <link rel="stylesheet" href="{{asset('dist/banner/scss/test.scss')}}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gsap/1.19.1/TweenMax.min.js"></script>
    <!-- JQVMap -->

    <!-- Theme style -->
    <link rel=" stylesheet" href="{{asset('dist/css/adminlte.min.css')}}">
    <link rel=" stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js">

    <link rel=" stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <!-- overlayScrollbars -->

    <!-- Daterange picker --
    <!-- summernote -->
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="cssSlider created with cssSlider, a free wizard program that helps you easily generate beautiful web slideshow" />

    <!-- carouselmoving -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <!-- carouselmoving -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <!-- carouselmoving -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!-- carouselmoving -->



    <!-- Start cssSlider.com -->
    <!-- Generated by cssSlider.com 2.1 -->


</head>

<body>
    <div class="">

        <header role="banner">
            <img id="logo-main" src="dist/img/lightghomo-01.png" width="200"  alt="Logo Thing main logo">
            <a href="#" class="btn btn-dark rounded py-3 px-3" style="color: white;float:right;margin:5px;">Sign up</a>
            <a href="#" class="btn btn-dark rounded py-3 px-3" style="color: white;float:right;margin:5px;">Sign in</a>
            <div class="container">
                <nav class="navbar navbar-inverse">
                    <div class="container-fluid">
                        <a href="#" id="len1" style="color:black;" class="nav-item nav-link active  hoverable">Home</a>
                        <a href="#" id="len2" style="color:black;" class="nav-link active  dropdown-toggle hoverable" data-bs-toggle="dropdown">Trips</a>
                        <div class="dropdown-menu">
                            <a href="#" style="color:black" class="dropdown-item active hoverable">Guided Tours</a>
                            <a href="#" style="color:black" class="dropdown-item active hoverable">Locations</a>
                            <a href="#" style="color:black" class="dropdown-item active hoverable">Honeymoon</a>
                            <a href="#" style="color:black" class="dropdown-item active hoverable">View All</a>
                        </div>
                        <a href="#" id="len3" style="color:black;" class="nav-item nav-link active hoverable ">Stays</a>
                        <a href="#" id="len4" style="color:black;" class="nav-item nav-link active hoverable ">Rentals</a>
                        <a href="#" id="len5" style="color:black;" class="nav-item nav-link active hoverable ">Food Blogs</a>
                        <a href="#" id="len6" style="color:black;" class="nav-item nav-link active hoverable ">About Us</a>
                        <a href="#" id="len7" style="color:black;" class="nav-item nav-link active hoverable ">Contact us</a>

                        <a href="#" id="len8" style="color:black;" class="nav-item nav-link active hoverable" tabindex="-1">Discover More</a>
                    </div>
                </nav>

            </div>
        </header><!-- header role="banner" -->
    </div>
    </div>
    @yield('content')
    <div class="content d-flex align-items-center bg-light">
        <!-- //content// -->

    </div>
    <footer class="footer-20192" style="margin-top: 200px;">
        <div class="site-section">
            <div class="container">

                <div class="cta d-block d-md-flex align-items-center px-5">
                    <div>
                        <h2 class="mb-0" style="color:white;">Ready for a next project?</h2>
                        <h3 class="text-light">Let's get started!</h3>
                    </div>
                    <div class="ml-auto">
                        <a href="#" class="btn btn-light rounded py-3 px-5" style="color: black;">Contact us</a>
                    </div>
                </div>
                <div class="row">

                    <div class="col-sm">
                        <span style="font-size:40px ;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;color:white"> GHOOMO PAKISTAN</span>
                        <p class="copyright">
                            <small>&copy; 2022</small>
                        </p>
                    </div>
                    <div class="col-sm">
                        <h3 style="color:white;">Quick Links</h3>
                        <ul class="list-unstyled links">
                            <li><a href="#">Trips</a></li>
                            <li><a href="#">Guided Tours</a></li>
                            <li><a href="#">Honeymoons</a></li>
                            <li><a href="#">Locations</a></li>
                            <li><a href="#">Stays</a></li>
                            <li><a href="#">Rentals</a></li>


                        </ul>
                    </div>
                    <div class="col-sm">
                        <h3 style="color:white;">Discover More</h3>
                        <ul class="list-unstyled links">
                            <li><a href="#">Historical Places</a></li>
                            <li><a href="#">Northern Areas </a></li>
                            <li><a href="#">Deserts</a></li>
                            <li><a href="#">Food Blogs</a></li>
                            <li><a href="#">To Do</a></li>
                        </ul>
                    </div>

                    <div class="col-md-3">
                        <h3 style="color:white;">Follow us</h3>
                        <ul class="list-unstyled social">
                            <li><a href="#"><span class="fab fa-facebook"> </span></a></li>
                            <li><a href="#"><span class="fab fa-twitter"></span></a></li>
                            <li><a href="#"><span class="fab fa-linkedin"></span></a></li>
                            <li><a href="#"><span class="fab fa-medium"></span></a></li>
                            <li><a href="#"><span class="fab fa-youtube"></span></a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </footer>


    <script>
        $(function() {
            var str = '#len'; //increment by 1 up to 1-nelemnts
            $(document).ready(function() {
                var i, stop;
                i = 1;
                stop = 8; //num elements
                setInterval(function() {
                    if (i > stop) {
                        return;
                    }
                    $('#len' + (i++)).toggleClass('bounce');
                }, 500)
            });
        });
    </script>

    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
</body>

</html>